application: somenumbers-148307
version: 1
runtime: python27
api_version: 1
threadsafe: false

handlers:

- url: /css
  static_dir: css

- url: /js
  static_dir: js

- url: /statements
  static_dir: statements
  application_readable: true

- url: /.*
  script: python/main.py
  # login: admin
  
#- url: /expenses
#  script: python/main.py
  # login: admin